ALTER TABLE movies ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'PENDING';
ALTER TABLE movies ADD COLUMN IF NOT EXISTS tags VARCHAR(255);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS ratings VARCHAR(50);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS credits TEXT;
TRUNCATE TABLE movies CASCADE;
