ALTER TABLE movies ADD COLUMN IF NOT EXISTS content_type VARCHAR(50) DEFAULT 'MOVIE';
ALTER TABLE movies ADD COLUMN IF NOT EXISTS trailer_src TEXT;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS runtime INT DEFAULT 0;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS episodes JSONB;
